"""empty message

Revision ID: 4aa2d1287004
Revises: b3cae1b7fe28
Create Date: 2018-04-07 11:29:50.661738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa2d1287004'
down_revision = 'b3cae1b7fe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('sid', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('value', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'value')
    op.drop_column('sessions', 'sid')
    # ### end Alembic commands ###
